### ISSUE TITLE
Change box shadow radius

### ISSUE THREAD

**Issue by BlitW0** [nortexoid/Borders-A-KMail-header-theme#1]
Box shadow is not visible when using dark themes. For example with Aritim Dark which has background color `#10151a`, the shadow is barely visible. I tried changing the spread radius to 2px instead of -2px, which made it much better.

Maybe you can try the header theme with other color themes and test this out better.

**Comment by nortexoid** [comment]
Thanks. I had not tried out dark color schemes since I don't use them but I'll have a tinker and see if I can find something that works well with both light and dark.

**Comment by nortexoid** [comment]
Since shadows don't work well on dark backgrounds, I've elevated the color of the header/body "cards" to a gray (30% tint of black). Should work with most dark themes. (I also slightly reduced the shadows.) It can be installed as a separate theme, "Borders Dark". What do you think? (Color scheme shown is Breeze Dark.)

![Screenshot_20210404_232630](https://user-images.githubusercontent.com/969567/113522069-171bc780-959e-11eb-80ac-ee71da9ab527.png)

**Comment by BlitW0** [comment]
The 30% tint of black may or may not fit some dark theme. Do stronger shadows look bad with light themes? Maybe try testing with some small set of light and dark themes instead of just Breeze Dark, and then the theme can be more refined. I really like the clean aesthetic of this theme (there aren't many anyways), but you should just test it a bit more.

**Comment by nortexoid** [comment]
I tested with enough themes to know that dark shadows aren't going to work well with most common dark themes that use a very dark view color, at least in my opinion. The gray is generic enough to work with many dark themes but if you want a perfect match you're better off customizing the background color of the header and body yourself, which is anyway very easy to do. If there were a way to use a tint percentage of the color scheme's view color, that would be ideal, but unfortunately there's no way to do that as far as I'm aware.

**Comment by BlitW0** [comment]
Yes, I understand. I guess we can consider the issue solved with separate themes for light and dark.
